services:
  app:
    build:
      context: .

    container_name: aldahim_app

    restart: unless-stopped

    env_file:
      - .env.prod.local

    environment:
      FIREBASE_CREDENTIALS: /run/secrets/firebase_credentials

    secrets:
      - firebase_credentials

    networks:
      - web
      - internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.aldahim.com`) || Host(`bo.aldahim.com`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  worker:
    image: app-app
    container_name: aldahim_worker
    restart: unless-stopped
    healthcheck:
      disable: true
    command:
      - php
      - bin/console
      - app:outbox:consume
      - --watch
      - --sleep=1
      - --limit=100
      - --format=json
    env_file:
      - .env.prod.local

    environment:
      FIREBASE_CREDENTIALS: /run/secrets/firebase_credentials

    secrets:
      - firebase_credentials

    networks:
      - internal

networks:
  web:
    external: true

  internal:
    external: true

secrets:
  firebase_credentials:
    file: ./config/firebase/service-account.json
