<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260926150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add address country metadata and an administrable delivery geography policy';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE geo_admin_area ADD country_code VARCHAR(2) DEFAULT 'GN' NOT NULL");
        $this->addSql("ALTER TABLE address ADD country_code VARCHAR(2) DEFAULT 'GN' NOT NULL");
        $this->addSql('CREATE INDEX idx_address_country_code ON address (country_code)');
        $this->addSql(<<<'SQL'
            CREATE TABLE delivery_geography_policy (
                id SMALLINT NOT NULL,
                mode VARCHAR(20) NOT NULL,
                allowed_country_codes JSONB NOT NULL,
                require_same_country BOOLEAN DEFAULT TRUE NOT NULL,
                enabled BOOLEAN DEFAULT TRUE NOT NULL,
                updated_by BIGINT DEFAULT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT chk_delivery_geography_policy_singleton CHECK (id = 1),
                CONSTRAINT chk_delivery_geography_policy_mode
                    CHECK (mode IN ('DOMESTIC_ONLY', 'SAME_COUNTRY', 'INTERNATIONAL')),
                CONSTRAINT fk_delivery_geography_policy_updated_by
                    FOREIGN KEY (updated_by) REFERENCES user_account (id) ON DELETE SET NULL
            )
            SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO delivery_geography_policy (
                id, mode, allowed_country_codes, require_same_country, enabled, updated_at
            ) VALUES (1, 'DOMESTIC_ONLY', '["FR", "GN"]'::jsonb, TRUE, TRUE, now())
            SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE delivery_geography_policy_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                changed_by BIGINT DEFAULT NULL,
                previous_value JSONB NOT NULL,
                new_value JSONB NOT NULL,
                changed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_delivery_geography_policy_history_changed_by
                    FOREIGN KEY (changed_by) REFERENCES user_account (id) ON DELETE SET NULL
            )
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE delivery_geography_policy_history');
        $this->addSql('DROP TABLE delivery_geography_policy');
        $this->addSql('DROP INDEX idx_address_country_code');
        $this->addSql('ALTER TABLE address DROP country_code');
        $this->addSql('ALTER TABLE geo_admin_area DROP country_code');
    }
}
