<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260926170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Persist delivery matching diagnostics and per-channel notification results';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE user_notification ADD delivery_id UUID DEFAULT NULL");
        $this->addSql("ALTER TABLE user_notification ADD mercure_status VARCHAR(20) DEFAULT 'PENDING' NOT NULL");
        $this->addSql('ALTER TABLE user_notification ADD mercure_last_error TEXT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_user_notification_delivery ON user_notification (delivery_id, user_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE delivery_matching_diagnostic (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                delivery_id UUID NOT NULL,
                driver_id BIGINT NOT NULL,
                online BOOLEAN NOT NULL,
                effective_online BOOLEAN NOT NULL,
                location_age_seconds INT DEFAULT NULL,
                accuracy_meters DOUBLE PRECISION DEFAULT NULL,
                distance_meters INT DEFAULT NULL,
                eligible BOOLEAN NOT NULL,
                rejection_reason VARCHAR(50) DEFAULT NULL,
                evaluated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id),
                CONSTRAINT fk_delivery_matching_driver FOREIGN KEY (driver_id)
                    REFERENCES user_account (id) ON DELETE CASCADE,
                CONSTRAINT chk_delivery_matching_distance CHECK (distance_meters IS NULL OR distance_meters >= 0)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_delivery_matching_driver ON delivery_matching_diagnostic (delivery_id, driver_id)');
        $this->addSql('CREATE INDEX idx_delivery_matching_delivery ON delivery_matching_diagnostic (delivery_id, eligible, distance_meters)');
        $this->addSql(<<<'SQL'
            UPDATE user_account
            SET phone = '+33781191499'
            WHERE regexp_replace(phone, '[^0-9]', '', 'g') IN ('33781191499', '0781191499', '781191499')
              AND NOT EXISTS (SELECT 1 FROM user_account existing WHERE existing.phone = '+33781191499')
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE delivery_matching_diagnostic');
        $this->addSql('DROP INDEX idx_user_notification_delivery');
        $this->addSql('ALTER TABLE user_notification DROP mercure_last_error');
        $this->addSql('ALTER TABLE user_notification DROP mercure_status');
        $this->addSql('ALTER TABLE user_notification DROP delivery_id');
    }
}
