# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# To list all registered routes, run the following command:
#   bin/console debug:router

back_office_pwa:
    path: /
    host: bo.aldahim.com
    controller: App\Controller\BackOfficeController::index
    methods: [GET]

back_office_pwa_fallback:
    path: /{path}
    host: bo.aldahim.com
    controller: App\Controller\BackOfficeController::index
    methods: [GET]
    requirements:
        path: '^(overview|providers|users|subscriptions|settings)$'

home:
    path: /
    controller: App\Controller\HomeController::index

dev_evolution_qr:
    path: /dev/evolution/qr
    controller: App\Controller\EvolutionQrController::show
    methods: [GET]

app_qrcode_show:
    path: /api/qrcode/{token}
    controller: App\Controller\QrCodeController::show
    methods: [GET]

app_qrcode_public:
    path: /a/{token}
    controller: App\Controller\QrCodeController::show
    methods: [GET]

app_generate_qrcode:
    path: /api/generate-qr
    controller: App\Controller\GenerateQrCodeController::generate
    methods: [POST]

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
